name: Deploy To Amazon S3
on: 
  push:
    branches: [master , main]

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{secrets.aws-access-key-id}}
          aws-secret-access-key: ${{secrets.aws-secret-access-key}}
          aws-region: ${{secrets.aws-region}}
      
      - name: Deploy portfolio to S3 bucket
        run: aws s3 sync . s3:://my-portfolio-bucket --delete