name: Deploy To Amazon S3
on: 
  push:
    branches: [master , main]

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
          AWS_REGION: ${{secrets.AWS_REGION}}
      
      - name: Deploy portfolio to S3 bucket
        run: aws s3 sync . s3:://${AWS_BUCKET_NAME} --delete